name: qmu-env
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python
  - numpy
prefix: /Users/lorrainedelaroque/anaconda3/envs/qmu-env
